### PR TITLE
Adds `az cr` commands: `catalog` and `tag`

### PR DESCRIPTION
**Pull request by DavidObando**
This is the first commit, just to light up `az cr` commands that talk to the registry. We'll need to improve this code in a few ways:
  - Handling error cases
  - Additional capabilities (such as filtering [client-side search] and RP integration)
  - Pretty printing the results

This also doesn't include any of the `az cr` commands that talk to the RP.

### CODE REVIEW

**Comment by SajayAntony** [comment]
/cc @sivagms @djyou 
:shipit:

**Comment by ahmetalpbalkan** [comment]
I think this is at the wrong level. I suggest this:

1. Move `az vm container` operations to `az vm container cluster {list,create,delete}`
2. Put this under `az vm container registry`

cc: @colemickens

**Comment by SajayAntony** [comment]
@ahmetalpbalkan why could this be under vm? Ross asked us to push this under `az cr`.

**Comment by colemickens** [comment]
Because the CLI should be intuitive to customers, not our org chart. Many container registry users are going to be using it with ACS. It seems to conceptually be a sibling of ACS, and thus the CLI should reflect that. No?

**Comment by ahmetalpbalkan** [comment]
@SajayAntony The service generic enough to be at the root level (as it can be used by websites as well as IaaS VMs). But it is more about discoverability & readability than being right there at the root level or being cryptic. I don't think container registries are big enough to deserve a root category yet.

Moreover `az vm container registry` tells me that “oh this has something to do with compute, and in there it has something to do with containers". Also Cole is right, most of the registry users will be deploying images to VMs, so why not put it under there?

I'm not a big fan of adding lots of stuff to the root namespace.

**Comment by SajayAntony** [comment]
@ahmetalpbalkan We should bring in Ross and Boris into this discussion. 
But for comparison of the CLI - docker is at the root level of glcoud and https://cloud.google.com/sdk/gcloud/reference/docker
And AWS - http://docs.aws.amazon.com/cli/latest/reference/ecr/create-repository.html
ACS is just one consumer of the registry and not the way to discover a repository is what I was thinking. But I'll leave that to the team to decide.

**Comment by DavidObando** [comment]
Also keep in mind that the registry can be used without Azure VMs or websites. We have deployed from this registry into other cloud providers and local network machines, and we regularly use it as part of our development process via the CI containers.

**Comment by SajayAntony** [comment]
FYI @rgardler
@DavidObando For this commit lets just get the features light up and see the outputs and will review later when the command should land once we integrate with the full CLI experience.

**Pull request merged**
