### PR TITLE
Support running an image without a context

### LINKED ISSUE #287: Enable Running an image - Proposal
Acr tasks only allows running a task file from a context and we want to enable storing the task file running without a context. 

There are 2 primary scenarios here 

1. Running a task with an image or encoded or stored file. 
1. Creating a Task with an image or encoded task file. 

## Running a task with an image 

|Description|Command | Notes|
|:-----------|:----------|:------|
| Running an image | `az acr run -t hello-world` | |
| Image with Args | `az acr run --image bash echo "hello-world" | Arguments follows image similar to docker run| 
| Image with timeout | `az acr run --timeout 100 --cmd nginx` | run properties come before image args` |

## Creating a Task with an Image or task file without a Source or GIT context 

|Description|Command | Notes|
|:-----------|:----------|:------|
| Create a task without context | `az acr task create -f task.yaml --values --import ` | Used to import values file from local context.  | 
| Create a task with an image | `az acr task create  --image hello-world` |  This can run an image against a and args as a file if needed.  |

### PR DESCRIPTION
**Pull request by NatalieYuGong**
Fixes #287 
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by djyou** [comment]
Do you want to send this PR to https://github.com/Azure/azure-cli? /cc @sajayantony

**Comment by sajayantony** [comment]
If we have covered all the scenarios and ACKd from folks on this team.

**Comment by northtyphoon** [comment]
Can you send PR to https://github.com/Azure/azure-cli?

**Comment by sajayantony** [comment]
@NatalieYuGong - could you also update the help commands on how to use -f - and run with --cmd
Also call out the impact of using /dev/null. 
Do we need to add test cases for these?

**Comment by NatalieYuGong** [comment]
> Can you send PR to https://github.com/Azure/azure-cli?
Sent https://github.com/Azure/azure-cli/pull/8814

**Comment by NatalieYuGong** [comment]
> @NatalieYuGong - could you also update the help commands on how to use -f - and run with --cmd
> Also call out the impact of using /dev/null.
> Do we need to add test cases for these?
Updated.
'Help' has the /dev/null being the default value for a contextless run/task. Will call out the impact later.
Added.

**Pull request closed without merging**
