### PR TITLE
Add build extensions and sync the CLI with the build extensions

### PR DESCRIPTION
**Pull request by ehotinger**
Add build extensions and sync the CLI with the build extensions

### CODE REVIEW

**Comment by ehotinger** [comment]
@djyou / @northtyphoon probably easier to review if you look commit-by-commit. It basically adds in the extension work @northtyphoon  did, updates the SDK for the CLI, and adds a bit of additional logic in the pre-existing `build.py`

**Comment by northtyphoon** [comment]
LGTM

**Review by djyou — APPROVED** [review]
I assume this commit https://github.com/AppPlatPerf/azure-cli/pull/62/commits/78d25e2fd4c3403210cd57c28f1eafdda4072f9d for extension folder is temporary as it duplicates code.

**Review by northtyphoon — APPROVED** [review]

**Comment by ehotinger** [comment]
@djyou yeah it's temporary

**Pull request merged**
